language: java

jdk:
- oraclejdk8

sudo: required 

services:
- docker

before_install:
- cd docker/dev
- docker-compose up -d
- docker ps -a

before_script:
- cd ../../src

script:
- mvn test -B
- cd ../docker/dev
- docker-compose stop
- docker-compose rm -f
- docker-compose up -d
- docker ps -a
- cd ../../src

notifications:
email: false