language: java

jdk:
- oraclejdk8

services:
- docker

before_install:
- cd docker/dev
- docker-compose up -d
- cd ../../src

script:
- mvn test -P test-consumer,test-business
- cd ../docker/dev
- docker-compose stop
- docker-compose rm -f
- docker-compose up -d
- docker ps -a
- cd ../../src

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

notifications:
email: false