language: java

jdk:
- oraclejdk8

sudo: required 

services:
- docker

before_install:
- cd docker/dev
- docker-compose up -d

before_script:
- cd ../../src

script:
- mvn test -Ptest-consumer,test-business
- cd ../docker/dev
- docker-compose stop
- docker-compose rm -f
- docker-compose up -d
- cd ../../src

after_success:
- mvn clean cobertura:cobertura coveralls:report

notifications:
email: false