language: java

jdk:
- oraclejdk8

services:
- docker

before_install:
- cd docker/dev
- docker-compose up -d
- cd ../../src

script:
- mvn test -B

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report


